name: tabee3_flutter
version: 2.8.0+19
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  calendar_timeline: ^1.0.4
  carousel_slider: ^5.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  file_picker: ^8.1.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  # flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.0.3
  html_editor_enhanced: ^2.4.0+1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_overlay: ^0.4.2
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  responsive_sizer: ^3.1.1
  screenshot: ^3.0.0
  table_calendar: ^3.0.5
  timeago: ^3.2.2
  timelines: ^0.1.0
  url_launcher: ^6.1.5
  zoom_widget: ^2.0.0
  flutter_inappwebview: ^6.1.5
  basic_utils: any
  firebase_core_platform_interface: ^5.3.0
  flutter_document_picker: any
  material_design_icons_flutter: ^7.0.7296
#  connectivity_plus: ^2.3.9
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.0.0
  firebase_auth: ^5.3.1
  pdf: ^3.6.0
  open_file: ^3.1.0











dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: Cairo Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
